import { supabase } from '../lib/supabase';
import { RazorpayOptions } from '../types';

export interface PaymentResult {
    success: boolean;
    error?: string;
    transactionId?: string;
}

export const COIN_PACKS = [
    { id: 'Pack_10', coins: 10, price: 10, save: 0 },
    { id: 'Pack_50', coins: 50, price: 45, save: 10 },
    { id: 'Pack_100', coins: 100, price: 80, save: 20 },
    { id: 'Pack_500', coins: 500, price: 350, save: 30 },
];

/**
 * Initiates a real payment via Razorpay + Supabase Edge Function
 */
export const initiatePayment = async (packId: string, userId: string, userEmail?: string, userPhone?: string): Promise<PaymentResult> => {
    const pack = COIN_PACKS.find(p => p.id === packId);
    if (!pack) return { success: false, error: 'Invalid pack selected' };

    console.log(`[Payment] Initializing Razorpay for ${pack.coins} coins (₹${pack.price})...`);

    try {
        // 1. Create Order via Edge Function (Secure)
        const { data: orderData, error: orderError } = await supabase.functions.invoke('create-razorpay-order', {
            body: {
                amount: pack.price,
                currency: 'INR',
                receipt: `rcpt_${Date.now()}`,
                userId: userId,
                coins: pack.coins
            }
        });

        if (orderError || !orderData || orderData.error) {
            console.error('[Payment] Order Creation Failed:', orderError || orderData?.error);
            throw new Error('Failed to initialize payment server.');
        }

        const { id: order_id, amount: order_amount, currency: order_currency } = orderData;
        console.log(`[Payment] Order Created: ${order_id}`);

        // 2. Open Razorpay Checkout
        return new Promise((resolve) => {
            const options: RazorpayOptions = {
                key: import.meta.env.VITE_RAZORPAY_KEY_ID, // Public Key from .env
                amount: order_amount,
                currency: order_currency,
                name: 'Chowkar',
                description: `Purchase ${pack.coins} Coins`,
                image: '/logo192.png',
                order_id: order_id, // Generated by backend
                handler: async (response: any) => {
                    console.log('[Payment] Payment Successful:', response);

                    // 3. SECURE: Do NOT credit wallet here.
                    // The 'razorpay-webhook' Edge Function will verify the signature and credit the wallet.
                    // We resolve success immediately so UI can show "Processing..." or similar.

                    resolve({
                        success: true,
                        transactionId: response.razorpay_payment_id
                    });
                },
                prefill: {
                    email: userEmail,
                    contact: userPhone
                },
                theme: {
                    color: '#10b981' // Chowkar Green
                },
                modal: {
                    ondismiss: () => {
                        console.log('[Payment] Checkout dismissed');
                        resolve({ success: false, error: 'Payment Cancelled' });
                    }
                }
            };

            const rzp1 = new window.Razorpay(options);
            rzp1.on('payment.failed', function (response: any) {
                console.error('[Payment] Failure:', response.error);
                resolve({ success: false, error: response.error.description || 'Payment Failed' });
            });
            rzp1.open();
        });

    } catch (err: any) {
        console.error('[Payment] Exception:', err);
        return { success: false, error: err.message || 'Unknown payment error' };
    }
};
