import { supabase } from '../lib/supabase';
import { logger } from '../lib/logger';
import { RazorpayOptions } from '../types';

export interface PaymentResult {
    success: boolean;
    error?: string;
    transactionId?: string;
    isInstant?: boolean;
}

export const COIN_PACKS = [
    { id: 'Pack_10', coins: 10, price: 10, save: 0 },
    { id: 'Pack_50', coins: 50, price: 45, save: 10 },
    { id: 'Pack_100', coins: 100, price: 80, save: 20 },
    { id: 'Pack_500', coins: 500, price: 350, save: 30 },
];

/**
 * Initiates a real payment via Razorpay + Supabase Edge Function
 */
export const initiatePayment = async (packId: string, userId: string, customAmount?: number, customCoins?: number, userEmail?: string, userPhone?: string): Promise<PaymentResult> => {
    let pack = COIN_PACKS.find(p => p.id === packId);

    // Support dynamic packs
    if (!pack && customAmount && customCoins) {
        pack = { id: packId, coins: customCoins, price: customAmount, save: 0 };
    }

    if (!pack) return { success: false, error: 'Invalid pack selected' };

    try {
        // 1. Create Order via Edge Function (Secure) with timeout
        logger.log(`[Payment] Initializing Razorpay for ${pack.coins} coins (₹${pack.price})...`);
        logger.log('[Payment] Calling create-razorpay-order Edge Function...');

        const invokePromise = supabase.functions.invoke('create-razorpay-order', {
            body: {
                amount: pack.price,
                currency: 'INR',
                receipt: `rcpt_${Date.now()}`,
                userId: userId,
                coins: pack.coins
            }
        });

        // Add 60-second timeout for Edge Function cold starts
        const timeoutPromise = new Promise((_, reject) =>
            setTimeout(() => reject(new Error('Edge Function call timed out after 60 seconds. Please try again as the server is now warming up.')), 60000)
        );

        const { data: orderData, error: orderError } = await Promise.race([invokePromise, timeoutPromise]) as any;

        logger.log('[Payment] Edge Function response received:', { orderData, orderError });

        if (orderError) {
            console.error('[Payment] Order Creation Error Object:', orderError);
            throw new Error(orderError.message || 'Failed to initialize payment server.');
        }

        if (!orderData || orderData.error) {
            console.error('[Payment] Order Data Error:', orderData?.error);
            throw new Error(orderData?.error || 'Failed to initialize payment server.');
        }

        const { id: order_id, amount: order_amount, currency: order_currency } = orderData;
        logger.log(`[Payment] Order Created: ${order_id}`);

        // 2. Open Razorpay Checkout
        return new Promise((resolve) => {
            const options: RazorpayOptions = {
                key: import.meta.env.VITE_RAZORPAY_KEY_ID, // Public Key from .env
                amount: order_amount,
                currency: order_currency,
                name: 'Chowkar',
                description: `Purchase ${pack.coins} Coins`,
                image: '/logo192.png',
                order_id: order_id, // Generated by backend
                handler: async (response: any) => {
                    logger.log('[Payment] Razorpay Callback Success:', response);

                    // 3. HYBRID VERIFICATION: 
                    // Call our direct verification endpoint for instant UX.
                    try {
                        logger.log('[Payment] Verifying directly via Edge Function...');
                        const { data: verifyData, error: verifyError } = await supabase.functions.invoke('verify-razorpay-payment', {
                            body: {
                                razorpay_order_id: response.razorpay_order_id,
                                razorpay_payment_id: response.razorpay_payment_id,
                                razorpay_signature: response.razorpay_signature,
                                userId: userId
                            }
                        });

                        if (verifyError || !verifyData || verifyData.error) {
                            console.warn('[Payment] Direct verification failed/delayed:', verifyError || verifyData?.error);
                            // We still resolve success=true because the Webhook will catch it anyway.
                            // But we return the data so UI knows if it was instant or not.
                            resolve({
                                success: true,
                                transactionId: response.razorpay_payment_id,
                                isInstant: false
                            });
                        } else {
                            logger.log('[Payment] Direct Verification Successful!');
                            resolve({
                                success: true,
                                transactionId: response.razorpay_payment_id,
                                isInstant: true
                            });
                        }
                    } catch (err) {
                        console.error('[Payment] Verification Exception:', err);
                        // Fallback to webhook-only success
                        resolve({ success: true, transactionId: response.razorpay_payment_id, isInstant: false });
                    }
                },
                prefill: {
                    email: userEmail,
                    contact: userPhone
                },
                theme: {
                    color: '#10b981' // Chowkar Green
                },
                modal: {
                    ondismiss: () => {
                        logger.log('[Payment] Checkout dismissed');
                        resolve({ success: false, error: 'Payment Cancelled' });
                    }
                }
            };

            const rzp1 = new (window as any).Razorpay(options);
            rzp1.on('payment.failed', function (response: any) {
                console.error('[Payment] Failure:', response.error);
                resolve({ success: false, error: response.error.description || 'Payment Failed' });
            });
            rzp1.open();
        });

    } catch (err: any) {
        console.error('[Payment] Exception:', err);
        return { success: false, error: err.message || 'Unknown payment error' };
    }
};

/**
 * Initiates a real payment for Premium Upgrade
 */
export const initiatePremiumPayment = async (userId: string, userEmail?: string, userPhone?: string): Promise<PaymentResult> => {
    try {
        const PREMIUM_PRICE = 99; // Fallback or imported

        logger.log(`[Payment] Initializing Premium Upgrade for ₹${PREMIUM_PRICE}...`);

        // 1. Create Order via Edge Function
        const { data: orderData, error: orderError } = await supabase.functions.invoke('create-razorpay-order', {
            body: {
                amount: PREMIUM_PRICE,
                currency: 'INR',
                receipt: `prem_${Date.now()}`,
                userId: userId,
                type: 'premium'
            }
        });

        if (orderError || !orderData || orderData.error) {
            throw new Error(orderError?.message || orderData?.error || 'Failed to initialize premium payment.');
        }

        const { id: order_id, amount: order_amount, currency: order_currency } = orderData;

        // 2. Open Razorpay Checkout
        return new Promise((resolve) => {
            const options: RazorpayOptions = {
                key: import.meta.env.VITE_RAZORPAY_KEY_ID,
                amount: order_amount,
                currency: order_currency,
                name: 'Chowkar Premium',
                description: 'Lifetime Premium Access',
                image: '/logo192.png',
                order_id: order_id,
                handler: async (response: any) => {
                    logger.log('[Payment] Premium Payment Successful:', response);
                    resolve({
                        success: true,
                        transactionId: response.razorpay_payment_id
                    });
                },
                prefill: {
                    email: userEmail,
                    contact: userPhone
                },
                theme: {
                    color: '#f59e0b' // Amber
                },
                modal: {
                    ondismiss: () => {
                        resolve({ success: false, error: 'Payment Cancelled' });
                    }
                }
            };

            const rzp1 = new (window as any).Razorpay(options);
            rzp1.open();
        });

    } catch (err: any) {
        console.error('[Payment] Premium Exception:', err);
        return { success: false, error: err.message || 'Unknown error' };
    }
};
